# Generated by Django 5.0.6 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('carrera', models.TextField()),
                ('num_parciales', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('web', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
        ),
    ]
