# Generated by Django 5.0.6 on 2024-06-27 14:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Sigue Impartiendose?'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='carrera',
            field=models.TextField(verbose_name='Nombre Carrera'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.TextField(verbose_name='Titulo del curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='num_parciales',
            field=models.IntegerField(verbose_name='Número de Parciales'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='web',
            field=models.URLField(verbose_name='Web para contenido'),
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción de la actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
